n = input('Digite um valor: ')
print(n)
print(type(n))
print(n.isnumeric())
n = input('Digite um valor: ')
print(n)
print(type(n))
print(n.isalpha())
n = str(input('Digite um valor: '))
print(n)
print(type(n))
n = float(input('Digite um valor: '))
print(n)
print(type(n))
